### ISSUE TITLE
Database with special characters in name

### ISSUE THREAD

**Issue by ahmedsajid** [glynnbird/couchwarehouse#33]
We run [Hyperledger Fabric](https://github.com/hyperledger/fabric) which uses CouchDB to store data. It has `$` and `_` characters in DB name. I'm unable to make couchwarehouse work with these DBs.
I have tried both urlencoding the characters as well as just passing the dbname as is with special characters.

```
$ couchwarehouse --version
1.6.4

$ couchwarehouse -u http://user:pass@localhost:5984 --db 'my_db$$name'
Run the following command to query your data warehouse:

  $ sqlite3 couchwarehouse.sqlite

Then in sqlite3, you can run queries e.g.:

  sqlite3> SELECT * FROM my_db$$name LIMIT 10;

Have fun!
p.s Press ctrl-C to stop monitoring for further changes
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_ERROR: near "~": syntax error
Emitted 'error' event at:



$ couchwarehouse -u http://user:pass@localhost:5984 --db my_db%24%24name
Run the following command to query your data warehouse:

  $ sqlite3 couchwarehouse.sqlite

Then in sqlite3, you can run queries e.g.:

  sqlite3> SELECT * FROM my_db%24%24name LIMIT 10;

Have fun!
p.s Press ctrl-C to stop monitoring for further changes
(node:168047) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/ahmed/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ahmed/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/home/ahmed/node_modules/axios/lib/adapters/http.js:231:9)
    at RedirectableRequest.emit (events.js:198:13)
    at RedirectableRequest._processResponse (/home/ahmed/node_modules/follow-redirects/index.js:399:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/home/ahmed/node_modules/follow-redirects/index.js:57:10)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
(node:168047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:168047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Curl works with urlencoded DB name. Example curl command,

```
curl -s --header "Content-Type: application/json" -d "$query_str" http://user:pass@localhost:5984/my_db%24%24name/_find
```

Any thoughts on making this work?

**Comment by glynnbird** [comment]
Hi there. I tried this locally on the latest version of `couchwarehouse` and it worked:

```sh
couchwarehouse --db 'sales$$records'
```
